services:
  salon-backend:
    image: salonstudio/salon-backend:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET:-salonstudio-secret}
      BASE_DOMAIN: ${BASE_DOMAIN}
      EVOLUTION_API_URL: ${EVOLUTION_API_URL:-http://evolution-api:8080}
      EVOLUTION_API_KEY: ${EVOLUTION_API_KEY}
      PORT: 5000
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      DB_USENAME: ${DB_USENAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB: ${DB}
      NODE_ENV: 'production'
    networks:
      - salonstudio
    labels:
      - "traefik.enable=true"
      # O Traefik agora escuta dinamicamente o subdomínio da API que você definir no Portainer
      - "traefik.http.routers.salon-backend.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.salon-backend.entrypoints=websecure"
      - "traefik.http.routers.salon-backend.tls=true"
      - "traefik.http.routers.salon-backend.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.salon-backend.loadbalancer.server.port=5000"

  salon-frontend:
    image: salonstudio/salon-frontend:latest
    restart: unless-stopped
    depends_on:
      - salon-backend
    networks:
      - salonstudio
    extra_hosts:
      - "${API_DOMAIN}:host-gateway"
    labels:
      - "traefik.enable=true"
      # O Traefik agora escuta dinamicamente o domínio do frontend (e subdomínios dos salões) que você definir no Portainer
      - "traefik.http.routers.salon-frontend.rule=Host(`${BASE_DOMAIN}`) || Host(`keilafrutuoso.${BASE_DOMAIN}`) || (HostRegexp(`*.${BASE_DOMAIN}`) && !Host(`api.${BASE_DOMAIN}`))"
      - "traefik.http.routers.salon-frontend.entrypoints=websecure"
      - "traefik.http.routers.salon-frontend.tls=true"
      - "traefik.http.routers.salon-frontend.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.salon-frontend.loadbalancer.server.port=80"

  salon-postgre:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USENAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB}
    networks:
      - salonstudio
    volumes:
      - postgres_data:/var/lib/postgresql/data
  evo_redis:
    image: redis:6-alpine
    container_name: evo_redis
    restart: unless-stopped
    networks:
      - salonstudio
    volumes:
      - redis_data:/data    
  salon-evolution:
    image: atendai/evolution-api:v2.1.1
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - salonstudio
    environment:
      - SERVER_URL=salonevolution.${BASE_DOMAIN}
      - DEL_INSTANCE=false
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://${DB_USENAME}:${DB_PASSWORD}@salon-postgre:${DB_PORT}/evolution
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - DATABASE_SAVE_DATA_LABELS=true
      - DATABASE_SAVE_DATA_HISTORIC=true
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_v2
      - RABBITMQ_ENABLED=false
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://evo_redis:6379/1
      - CACHE_REDIS_PREFIX_KEY=evolution_v2
      - CACHE_REDIS_SAVE_INSTANCES=false
      - CACHE_LOCAL_ENABLED=false
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == evolution-manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.salon-evolution.rule=Host(`salonevolution.${BASE_DOMAIN}`)
        - traefik.http.routers.salon-evolution.entrypoints=websecure
        - traefik.http.routers.salon-evolution.tls.certresolver=letsencryptresolver
        - traefik.http.routers.salon-evolution.service=salon-evolution
        - traefik.http.services.salon-evolution.loadbalancer.server.port=8080
        - traefik.http.services.salon-evolution.loadbalancer.passHostHeader=true
      
networks:
  salonstudio:
    external: true

volumes:
  postgres_data:
  evolution_instances:
    external: true
    name: evolution_v2_data
  redis_data:
    name: evo_redis_data