services:
  salon-backend:
    image: salonstudio/salon-backend:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET:-salonstudio-secret}
      BASE_DOMAIN: ${BASE_DOMAIN}
      EVOLUTION_API_URL: ${EVOLUTION_API_URL:-http://evolution-api:8080}
      EVOLUTION_API_TOKEN: ${EVOLUTION_API_TOKEN}
      PORT: 5000
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      DB_USENAME: ${DB_USENAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB: ${DB}
      NODE_ENV: 'production'
    networks:
      - salonstudio
    labels:
      - "traefik.enable=true"
      # O Traefik agora escuta dinamicamente o subdomínio da API que você definir no Portainer
      - "traefik.http.routers.salon-backend.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.salon-backend.entrypoints=websecure"
      - "traefik.http.routers.salon-backend.tls=true"
      - "traefik.http.routers.salon-backend.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.salon-backend.loadbalancer.server.port=5000"

  salon-frontend:
    image: salonstudio/salon-frontend:latest
    restart: unless-stopped
    depends_on:
      - salon-backend
    networks:
      - salonstudio
    extra_hosts:
      - "${API_DOMAIN}:host-gateway"
    labels:
      - "traefik.enable=true"
      # O Traefik agora escuta dinamicamente o domínio do frontend (e subdomínios dos salões) que você definir no Portainer
      - "traefik.http.routers.salon-frontend.rule=Host(`${BASE_DOMAIN}`) || Host(`keilafrutuoso.${BASE_DOMAIN}`) || Host(`demostrativo.${BASE_DOMAIN}`) || Host(`deboranails.${BASE_DOMAIN}`)"
      - "traefik.http.routers.salon-frontend.entrypoints=websecure"
      - "traefik.http.routers.salon-frontend.tls=true"
      - "traefik.http.routers.salon-frontend.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.salon-frontend.loadbalancer.server.port=80"

  salon-postgre:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USENAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB}
    networks:
      - salonstudio
    volumes:
      - postgres_data:/var/lib/postgresql/data
  reminder-worker:
    image: salonstudio/salon-backend:latest
    container_name: reminder-worker
    restart: always
    command: [ "node", "src/worker-runner.js" ]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DB_USENAME: ${DB_USENAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB: ${DB}
      EVOLUTION_API_URL: ${EVOLUTION_API_URL:-http://evolution-api:8080}
      EVOLUTION_API_TOKEN: ${EVOLUTION_API_TOKEN}
      NODE_ENV: 'production'
    depends_on:
      - salon-postgre
    networks:
      - salonstudio
networks:
  salonstudio:
    external: true

volumes:
  postgres_data:
